### ISSUE TITLE
For Jenny: How to organize Airtable once we start adding Hugo/Nebula?

### ISSUE THREAD

**Issue by jenny8lee** [writingatlas/change-requests#19]
Question, problem (for @eric-zhizu and @eob to help me with). We are going to "run out" of BASFF stories which have publicly available URLs soon. We can start with Nebula/Hugo Short Stories nomiees. But a story can have multiple awards (and also be in BASFF). How to deal with?

Right now, I have Veronica only doing URL research on stories prior to BASFF

**Comment by eob** [comment]
Closing -- I think this issue is resolved.
