### ISSUE TITLE
Double "journalism"  tag (blue and plain)

### ISSUE THREAD

**Issue by jenny8lee** [writingatlas/change-requests#33]
![image](https://user-images.githubusercontent.com/162240/107071073-2d7df080-67b2-11eb-9c0a-764af19a7ebf.png)

We have a plain journalism tag and a blue journalism tag. What is the difference, and is our data work impacting that?

**Comment by eob** [comment]
Nice catch @jenny8lee ! Fixed

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/63262/108810884-13804280-75e7-11eb-91bc-81471689a439.png">
