### ISSUE TITLE
Add a line "Need help clearing rights? Contact us!"

### ISSUE THREAD

**Issue by jenny8lee** [writingatlas/change-requests#37]
"Find rights-available stories to produce and adapt.
Our team of readers, producers, and data experts can help you find exactly the stories your production team is looking for.
Reach out to me."

"Need help clearing short story rights for screen adaptation, education uses or translation?
Our team of readers, researchers and data experts can help you with the process.
Contact us!"

**Comment by eob** [comment]
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/63262/108810801-e895ee80-75e6-11eb-9ae5-7dc2ca57b4e2.png">

Also updated so that it points to email instead of login.
