### ISSUE TITLE
All the author data has disappeared on writingatlas.com!

### ISSUE THREAD

**Issue by jenny8lee** [writingatlas/change-requests#62]
1) All the stories don't have author info

2) All the authors have "no stories found"
![image](https://user-images.githubusercontent.com/162240/113917385-258cfd80-97af-11eb-9f5c-15173aa8edd5.png)

Example:
https://writingatlas.com/author/yoon-ha-lee
![image](https://user-images.githubusercontent.com/162240/113917140-d777fa00-97ae-11eb-970e-b7454a024cb0.png)

**Comment by eob** [comment]
Fixed
